import { sort } from './sort.js';
import { problems } from './problems.js';
import { functional } from './functional.js';
import { SinglyLinkedList } from './DS/SinglyLinkedList';
import { BinarySearchTree } from './DS/trees';
import { Graph } from './DS/Graph';
// functional();
// problems();
sort();
BinarySearchTree();
Graph();
